version: '3'

services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER='crmdev' 
      - MYSQL_PASSWORD='crmdev'
    ports:
      # - "${MYSQL_PORT}:3306"
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  python:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=crmproject.settings_local
    volumes:
      - ./workdir:/code
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    build: build/nginx
    volumes:
      - ./workdir:/code
    ports:
        - '${WEB_HOST}:80'
    depends_on:
        - python
        - db